tags:
  - name: Index
    description: index API
  - name: Users
    description: users API
  - name: Auth
    description: auth API

paths:
  ## INDEX
  # [GET] status
  /status:
    get:
      tags:
        - Index
      summary: Get Status
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"

  ## AUTH
  # [POST] auth/login
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/loginUserDto"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad Request"
        401:
          description: "Wrong authentication token"
        404:
          description: "Authentication token missing"
        500:
          description: "Server Error"

  # [POST] auth/register
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register
      requestBody:
        description: user Data
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/registerUserDto"
      responses:
        201:
          description: "Created"
        400:
          description: "Bad Request"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

  ## USERS
  # [GET] users
  /users:
    get:
      security:
        - bearerAuth: []
      tags:
        - Users
      summary: Find All Users
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"

  # [GET] users/username
  /users/{username}:
    get:
      security:
        - bearerAuth: []
      tags:
        - Users
      summary: Find User By username
      parameters:
        - name: username
          in: path
          description: User username
          required: true
      responses:
        200:
          description: "OK"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

    # [PUT] users/id
    put:
      security:
        - bearerAuth: []
      tags:
        - Users
      summary: Update User By username
      parameters:
        - name: username
          in: path
          description: user username
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/definitions/users"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad Request"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

    # [DELETE] users/id
    delete:
      security:
        - bearerAuth: []
      tags:
        - Users
      summary: Delete User By username
      parameters:
        - name: username
          in: path
          description: user username
          required: true
      responses:
        200:
          description: "OK"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

  ## SPOTS
  # [GET] spots
  /spots:
    get:
      security:
        - bearerAuth: []
      tags:
        - Spots
      summary: Find All Spots
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"

    # [POST] spots
    post:
      security:
        - bearerAuth: []
      tags:
        - Spots
      summary: Add Spot
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/Spot"
      responses:
        201:
          description: "Created"
        400:
          description: "Bad Request"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

  # [GET] spots/id
  /spots/{id}:
    get:
      security:
        - bearerAuth: []
      tags:
        - Spots
      summary: Find Spot By Id
      parameters:
        - name: id
          in: path
          description: Spot Id
          required: true
      responses:
        200:
          description: "OK"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

    # [PUT] spots/id
    put:
      security:
        - bearerAuth: []
      tags:
        - Spots
      summary: Update Spot By Id
      parameters:
        - name: id
          in: path
          description: spot Id
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/definitions/spots"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad Request"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

    # [DELETE] spots/id
    delete:
      security:
        - bearerAuth: []
      tags:
        - Spots
      summary: Delete Spot By Id
      parameters:
        - name: id
          in: path
          description: spot Id
          required: true
      responses:
        200:
          description: "OK"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

  ## RESERVATIONS
  # [GET] reservations
  /reservations:
    get:
      security:
        - bearerAuth: []
      tags:
        - Reservations
      summary: Find All Reservations
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"

    # [POST] spots
    post:
      security:
        - bearerAuth: []
      tags:
        - Reservations
      summary: Add Reservation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/Reservation"
      responses:
        201:
          description: "Created"
        400:
          description: "Bad Request"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

  # [GET] reservations/id
  /reservations/{id}:
    get:
      security:
        - bearerAuth: []
      tags:
        - Reservations
      summary: Find Reservation By Id
      parameters:
        - name: id
          in: path
          description: Reservation Id
          required: true
      responses:
        200:
          description: "OK"
        409:
          description: "Conflict"
        500:
          description: "Server Error"
    # [PUT] reservations/id
    put:
      security:
        - bearerAuth: []
      tags:
        - Reservations
      summary: Update Reservation By Id
      parameters:
        - name: id
          in: path
          description: reservation Id
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/definitions/reservations"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad Request"
        409:
          description: "Conflict"
        500:
          description: "Server Error"
    # [DELETE] reservations/id
    delete:
      security:
        - bearerAuth: []
      tags:
        - Reservations
      summary: Delete Reservation By Id
      parameters:
        - name: id
          in: path
          description: reservation Id
          required: true
      responses:
        200:
          description: "OK"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

  /reservations/getByUser/{username}:
    get:
      security:
        - bearerAuth: []
      tags:
        - Reservations
      summary: Find Reservation By username
      parameters:
        - name: username
          in: path
          description: user's username
          required: true
      responses:
        200:
          description: "OK"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

  /reservations/getBySpot/{spotId}:
    get:
      security:
        - bearerAuth: []
      tags:
        - Reservations
      summary: Find Reservation By spotId
      parameters:
        - name: spotId
          in: path
          description: spot's spotId
          required: true
      responses:
        200:
          description: "OK"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

# definitions
definitions:
  ## Users
  User:
    type: object
    required:
      - email
      - password
    properties:
      email:
        type: string
        description: user Email
      password:
        type: string
        description: user Password
  loginUserDto:
    type: object
    required:
      - username
      - password
    properties:
      username:
        type: string
        description: user username
      password:
        type: string
        description: user Password
  registerUserDto:
    type: object
    required:
      - username
      - email
      - password
      - firstName
      - lastName
    properties:
      username:
        type: string
        description: user username
      email:
        type: string
        description: user email
      password:
        type: string
        description: user Password
      firstName:
        type: string
        description: user First Name
      lastName:
        type: string
        description: user Last Name
  ## Spots
  Spot:
    type: object
    required:
      - id
      - state
    properties:
      id:
        type: string
        description: spot id
      state:
        type: string
        description: spot state
  ## Reservations
  Reservation:
    type: object
    required:
      - user
      - spot
      - createdAt
      - startedAt
      - endedAt
    properties:
      user:
        type: string
        description: user object
      spot:
        type: string
        description: spot object
      createdAt:
        type: string
        format: date-time
        description: reservation creation date
      startedAt:
        type: string
        format: date-time
        description: reservation start date
      endedAt:
        type: string
        format: date-time
        description: reservation end date
schemes:
  - https
  - http
