tags:
  - name: Index
    description: index API
  - name: Users
    description: users API
  - name: Auth
    description: auth API

paths:
  ## INDEX
  # [GET] status
  /status:
    get:
      tags:
        - Index
      summary: Get Status
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"

  ## USERS
  # [GET] users
  /users:
    get:
      security:
        - bearerAuth: []
      tags:
        - Users
      summary: Find All Users
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"

    # [POST] users
    post:
      security:
        - bearerAuth: []
      tags:
        - Users
      summary: Add User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/registerUserDto"
      responses:
        201:
          description: "Created"
        400:
          description: "Bad Request"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

  # [GET] users/id
  /users/{id}:
    get:
      security:
        - bearerAuth: []
      tags:
        - Users
      summary: Find User By Id
      parameters:
        - name: id
          in: path
          description: User Id
          required: true
      responses:
        200:
          description: "OK"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

    # [PUT] users/id
    put:
      security:
        - bearerAuth: []
      tags:
        - Users
      summary: Update User By Id
      parameters:
        - name: id
          in: path
          description: user Id
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/definitions/users"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad Request"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

    # [DELETE] users/id
    delete:
      security:
        - bearerAuth: []
      tags:
        - Users
      summary: Delete User By Id
      parameters:
        - name: id
          in: path
          description: user Id
          required: true
      responses:
        200:
          description: "OK"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

  ## SPOTS
  # [GET] spots
  /spots:
    get:
      security:
        - bearerAuth: []
      tags:
        - Spots
      summary: Find All Spots
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"

    # [POST] spots
    post:
      security:
        - bearerAuth: []
      tags:
        - Spots
      summary: Add Spot
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/Spot"
      responses:
        201:
          description: "Created"
        400:
          description: "Bad Request"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

  # [GET] spots/id
  /spots/{id}:
    get:
      security:
        - bearerAuth: []
      tags:
        - Spots
      summary: Find Spot By Id
      parameters:
        - name: id
          in: path
          description: Spot Id
          required: true
      responses:
        200:
          description: "OK"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

    # [PUT] spots/id
    put:
      security:
        - bearerAuth: []
      tags:
        - Spots
      summary: Update Spot By Id
      parameters:
        - name: id
          in: path
          description: spot Id
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/definitions/spots"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad Request"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

    # [DELETE] spots/id
    delete:
      security:
        - bearerAuth: []
      tags:
        - Spots
      summary: Delete Spot By Id
      parameters:
        - name: id
          in: path
          description: spot Id
          required: true
      responses:
        200:
          description: "OK"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

  ## AUTH
  # [POST] auth/login
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/loginUserDto"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad Request"
        401:
          description: "Wrong authentication token"
        404:
          description: "Authentication token missing"
        500:
          description: "Server Error"

  # [POST] auth/signin
  /auth/signin:
    post:
      tags:
        - Auth
      summary: Register
      requestBody:
        description: user Data
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/registerUserDto"
      responses:
        201:
          description: "Created"
        400:
          description: "Bad Request"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

  # [POST] auth/logout
  /auth/logout:
    security:
      - bearerAuth: []
    post:
      tags:
        - Auth
      summary: Logout
      responses:
        200:
          description: "OK"
        401:
          description: "Unauthorized"
        500:
          description: "Server Error"

# definitions
definitions:
  ## Users
  users:
    type: object
    required:
      - email
      - password
    properties:
      email:
        type: string
        description: user Email
      password:
        type: string
        description: user Password
  loginUserDto:
    type: object
    required:
      - email
      - password
    properties:
      email:
        type: string
        description: user Email
      password:
        type: string
        description: user Password
  registerUserDto:
    type: object
    required:
      - email
      - password
      - firstName
      - lastName
    properties:
      email:
        type: string
        description: user Email
      password:
        type: string
        description: user Password
      firstName:
        type: string
        description: user First Name
      lastName:
        type: string
        description: user Last Name
  ## Spots
  Spot:
    type: object
    required:
      - numero
      - etat
    properties:
      numero:
        type: number
        description: spot number
      etat:
        type: string
        description: spot state

schemes:
  - https
  - http
