tags:
  - name: Index
    description: index API
  - name: Users
    description: users API
  - name: Auth
    description: auth API

paths:
  ## INDEX
  # [GET] status
  /status:
    get:
      tags:
        - Index
      summary: Get Status
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"

  ## USERS
  # [GET] users
  /users:
    get:
      security:
        - bearerAuth: []
      tags:
        - Users
      summary: Find All Users
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"

    # [POST] users
    post:
      security:
        - bearerAuth: []
      tags:
        - Users
      summary: Add User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/registerUserDto"
      responses:
        201:
          description: "Created"
        400:
          description: "Bad Request"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

  # [GET] users/id
  /users/{id}:
    get:
      security:
        - bearerAuth: []
      tags:
        - Users
      summary: Find User By Id
      parameters:
        - name: id
          in: path
          description: User Id
          required: true
      responses:
        200:
          description: "OK"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

    # [PUT] users/id
    put:
      security:
        - bearerAuth: []
      tags:
        - Users
      summary: Update User By Id
      parameters:
        - name: id
          in: path
          description: user Id
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/definitions/users"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad Request"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

    # [DELETE] users/id
    delete:
      security:
        - bearerAuth: []
      tags:
        - Users
      summary: Delete User By Id
      parameters:
        - name: id
          in: path
          description: user Id
          required: true
      responses:
        200:
          description: "OK"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

  ## PLACES
  # [GET] places
  /places:
    get:
      security:
        - bearerAuth: []
      tags:
        - Places
      summary: Find All Places
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"

    # [POST] places
    post:
      security:
        - bearerAuth: []
      tags:
        - Places
      summary: Add Place
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/Place"
      responses:
        201:
          description: "Created"
        400:
          description: "Bad Request"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

  # [GET] places/id
  /places/{id}:
    get:
      security:
        - bearerAuth: []
      tags:
        - Places
      summary: Find Place By Id
      parameters:
        - name: id
          in: path
          description: Place Id
          required: true
      responses:
        200:
          description: "OK"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

    # [PUT] places/id
    put:
      security:
        - bearerAuth: []
      tags:
        - Places
      summary: Update Place By Id
      parameters:
        - name: id
          in: path
          description: place Id
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/definitions/places"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad Request"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

    # [DELETE] places/id
    delete:
      security:
        - bearerAuth: []
      tags:
        - Places
      summary: Delete Place By Id
      parameters:
        - name: id
          in: path
          description: place Id
          required: true
      responses:
        200:
          description: "OK"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

  ## AUTH
  # [POST] auth/login
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/loginUserDto"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad Request"
        401:
          description: "Wrong authentication token"
        404:
          description: "Authentication token missing"
        500:
          description: "Server Error"

  # [POST] auth/signin
  /auth/signin:
    post:
      tags:
        - Auth
      summary: Register
      requestBody:
        description: user Data
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/registerUserDto"
      responses:
        201:
          description: "Created"
        400:
          description: "Bad Request"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

  # [POST] auth/logout
  /auth/logout:
    security:
      - bearerAuth: []
    post:
      tags:
        - Auth
      summary: Logout
      responses:
        200:
          description: "OK"
        401:
          description: "Unauthorized"
        500:
          description: "Server Error"

# definitions
definitions:
  ## Users
  users:
    type: object
    required:
      - email
      - password
    properties:
      email:
        type: string
        description: user Email
      password:
        type: string
        description: user Password
  loginUserDto:
    type: object
    required:
      - email
      - password
    properties:
      email:
        type: string
        description: user Email
      password:
        type: string
        description: user Password
  registerUserDto:
    type: object
    required:
      - email
      - password
      - firstName
      - lastName
    properties:
      email:
        type: string
        description: user Email
      password:
        type: string
        description: user Password
      firstName:
        type: string
        description: user First Name
      lastName:
        type: string
        description: user Last Name
  ## Places
  Place:
    type: object
    required:
      - numero
      - etat
    properties:
      numero:
        type: number
        description: place number
      etat:
        type: string
        description: place state

schemes:
  - https
  - http
